spring:
  application:
    name: Project_Management
  datasource:
    url: jdbc:postgresql://localhost:5432/security_test
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: aaabhi8888@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  jwt-secret: JWTSecretKey
  jwt-expiration-milliseconds: 60480000
logging:
  level:
    root: INFO
    com.example.customSe: DEBUG
otp:
  channel: APP

